package gt.gob.sib.portal.sne.menu;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MenuAplicaciones extends HorizontalLayout {
	protected CssLayout navBarContainer;
	protected Button menuButton;
	protected CssLayout menu;
	protected Button notificaciones;
	protected Button registros;
	protected HorizontalLayout header;
	protected Button btnMenu;
	protected CssLayout content;

	public MenuAplicaciones() {
		Design.read(this);
	}
}
